### ISSUE TITLE
Increase token length, or make it harder to brute-force tokens.

### ISSUE THREAD

**Issue by dseomn** [ocean90/public-post-preview#10]
With a 5 byte token and 48 hour window, it would take `256^5 / (48*3600)` (about 6 million) qps to have a 100% chance of accessing the preview. 6 million qps is very high, but not outrageously high. If it's trivial, would you mind increasing the token length and/or adding a ~1 second sleep before the verification code, to make a brute force attack harder?

**Comment by ocean90** [comment]
You'd also need an ID of a post that's currently active for preview. You could reduce the life time of the nonce but if you're that worried about brute force attacks you probably should not use the plugin.
