### ISSUE TITLE
Preview page is broken

### ISSUE THREAD

**Issue by shummel-brunner** [ocean90/public-post-preview#171]
We are having issues with the plugin, but don't know if there is a conflict with other plugins. Our site is on WordPress 6.2.x. Is you plugin compatible with that version? We updated a bunch of plugins and that's when the preview broke. Most of the content is missing from the page when save a new draft but the CSS for the content that is there seems fine. The first draft preview will display correctly but updates to the draft after that have missing content on the preview. We have not altered the code in the plugin. Here is a list of plugins that got updated when the issue started.

- ACF Pro
- AYS Popup Box
- Contact Form 7 Conditional Fields
- Contact Form 7
- FacetWP
- Relavnssi Premium
- Safe SVG
- Simple Page Ordering
- User Role Editor
- White Label CMS
- Wordfence
- WordPress SEO 
- WordPress SEO Premium

**Comment by ocean90** [comment]
Unfortunately, I can't help you debugging the issue. Please try disabling all plugins and reactivate them one by one to identify the problematic plugin. The [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/) may help you there.
