### ISSUE TITLE
Preview doesn't show any Beaver Builder content

### ISSUE THREAD

**Issue by codente** [ocean90/public-post-preview#172]
Starting in version 2.7.4.3 of Beaver Builder, there are security fixes that prevent non-public posts (like drafts) from being rendered by BB to people without access.  

So this plugin stops working with Beaver Builder

There is a filter that can be used to adjust this though and we came up with the following:

```
add_filter( 'fl_render_content_by_id_can_view', function( $can_view, $post_id ) {
	if ( class_exists( 'DS_Public_Post_Preview' ) ) {
		$post_ids = get_option( 'public_post_preview', array() );
		$post_ids = array_map( 'intval', $post_ids );
		$can_view = ( in_array( $post_id, $post_ids ) ) ? true : $can_view;
	}
	return $can_view;
}, 10, 2 );
```

Would you be interested in adding this to your plugin for compatibility?

**Comment by ewelin34** [comment]
Can confirm this fix works! Thanks for being sharing!

**Comment by jimbowermandesign** [comment]
I apologize in advance for this (newbie here), where can I download the plug-in with this fix? I inherited a site using Beaver Builder and this is driving me nuts.

**Comment by allanminium** [comment]
@jimbowermandesign add it to the functions.php file.

**Comment by ocean90** [comment]
Thank you for providing the snippet! Everyone who is also using Beaver Builder, please copy the above snippet to your theme's `function.php`.
