### ISSUE TITLE
Feature request: add a filter to control which post types can use Public Post Preview

### ISSUE THREAD

**Issue by benlk** [ocean90/public-post-preview#174]
https://github.com/ocean90/public-post-preview/blob/28e037449977f0135c486e19968e580349fac14f/public-post-preview.php#L193-L197

This list of post-types should be filterable to allow removing post types that the user does not want to enable PPP on.

**Comment by ocean90** [comment]
The filter was added in https://github.com/ocean90/public-post-preview/commit/697e396cce9cec60f393c8694d76cf9e4ffa4822.

**Comment by benlk** [comment]
Thank you!
