### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by stuartshields** [ocean90/public-post-preview#23]
Is there a way to load the new internationalization files for Gutenberg? These files are done via `json`.

- Gutenberg doesn't use `mo` files, you need to use json by `wp i18n make-json`
- You also need to call `wp_set_script_translations`
- `gutenberg_get_jed_locale_data` is deprecated as of version 5.2 (I believe)

I'm just wondering if there are any plans in the pipeline to update how the Gutenberg internationalization stuff is done.

**Comment by ocean90** [comment]
Thanks for the reminder. I'll update it to replace the use of `gutenberg_get_jed_locale_data()`.
