### ISSUE TITLE
Provide "Open Public Preview" link in the Admin listing UI

### ISSUE THREAD

**Issue by topher1kenobe** [ocean90/public-post-preview#49]
In the admin listing, with the links that appear on hover, make an "Open Public Preview" link.

**Comment by ocean90** [comment]
If you have access to the admin list, why would you need this link? It's basically the same as the existing "Preview" link.

**Comment by topher1kenobe** [comment]
But the existing Preview link isn't a Public Preview link. If I want a Public one I have to click Edit and wait for the entire editing UI to load.

**Comment by nekohayo** [comment]
Hi there! I've been using your extension for a long time, and I was about to report this exact same ticket now. The usecase here is being able to quickly share preview links after the fact, to other people, without having to enter editing mode for each post (which is very slow and cumbersome/inefficient in comparison).

Yet, in the general posts list in the admin view, (i.e. `/wp-admin/edit.php?post_type=post` and such), your plugin already appends " **— Public preview**" to post titles... so why not just hyperlink that string with the public preview link, and maybe also say the expiry date in the title attribute. So for example, `title="Right-click and copy this link to share it with others. This link expires in %d hours."`

Alternatively you could have a "| Public preview link" hyperlink next to the " | Preview" link on hover below the title, but I'm not sure if that's technically feasible, and it's probably less elegantly efficient as simply hyperlinking the existing "— Public preview" string.
